name: real_push_image

image_shape: [3, 240, 320]
dataset_path: 2d_data

shape_meta: &shape_meta
  # acceptable types: rgb, low_dim
  obs:
    camera_0:
      shape: ${task.image_shape}
      type: rgb
    # camera_1:
    #   shape: ${task.image_shape}
    #   type: rgb
    # camera_2:
    #   shape: ${task.image_shape}
    #   type: rgb
    # camera_3:
    #   shape: ${task.image_shape}
    #   type: rgb
    # camera_4:
    #   shape: ${task.image_shape}
    #   type: rgb
    agent_pos:
      shape: [9]
      type: low_dim
  action: 
    shape: [9]

env_runner:
  _target_: diffusion_policy.env_runner.real_pusht_image_runner.RealPushTImageRunner

dataset:
  _target_: diffusion_policy.dataset.push_image_dataset.RealPushImageDataset
  shape_meta: *shape_meta
  dataset_path: ${task.dataset_path}
  horizon: ${horizon}
  pad_before: ${eval:'${n_obs_steps}-1+${n_latency_steps}'}
  pad_after: ${eval:'${n_action_steps}-1'}
  n_obs_steps: ${dataset_obs_steps}
  n_latency_steps: ${n_latency_steps}
  use_cache: True
  seed: 42
  val_ratio: 0.00
  max_train_episodes: null
  delta_action: False

